name: Deploy to Korifi

on:
  push:
  workflow_dispatch:

jobs:
  deploy_to_korifi:
    runs-on: ubuntu-latest
    
    container:
      image: 172.17.133.1:5000/cloudfoundry/cli:latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          apk add --no-cache gettext
      
      - name: Setup kubectl config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECTL_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
      
      - name: Setup manifest file
        run: |
          echo "${{ secrets.MANIFEST_YML }}" > manifest.yml
      
      - name: Verify CF CLI
        run: |
          cf --version
          cat ~/.kube/config
      
      - name: Deploy to Cloud Foundry
        run: |
          set -x
          cf api api.sharina.tech --skip-ssl-validation
          cf login -u default
          cf target -o shahd -s dev
          cf buildpacks
          envsubst < manifest.yml > manifest_processed.yaml
          cf push -f manifest_processed.yaml
          set +x

